on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v7

      - name: 💾 Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.4"
          dev: no
          args: --profile --ignore-platform-reqs
          command: install

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: 📦 Install Node.js dependencies
        run: npm install

      - name: 🛠️ Build project
        run: npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          local-dir: ./
          server-dir: ${{ secrets.FTP_PATH }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/public/index.php
            **/DOCKER*
            **/DOCKER*/**
            **/docker*
            **/docker*/**
            **/Docker*
            **/Docker*/**
            **/output.log
            **/.agents/**
            **/tests/**
            **/skills-lock.json
            **/README.md
            **/LICENSE
            **/.prettierrc
            **/.editorconfig
